### ISSUE TITLE
Conflict with NSViewController in macOS 10.13 / Swift 4

### ISSUE THREAD

**Issue by lhc70000** [shpakovski/MASPreferences#54]
First of all thanks a lot for this project.

As stated in README, there is a workaround for implementing the property `identifier` in Swift:

> When using Swift you need to override the identifier from MASPreferencesViewController the following to be compatible with the mutable identifier String? in NSViewController

However in macOS 10.13 SDK and Swift 4, the type of `identifier` from `NSViewController` has been changed from `String?` to `NSUserInterfaceItemIdentifier?`, which made the above trick no longer working.

**Comment by shpakovski** [comment]
Thanks a lot for the heads up! So we should rename `identifier` into `toolbarItemIdentifier`, right?.

**Comment by lhc70000** [comment]
Yes, it should be a possible solution.

Alternatively, simply changing

```objc
@property (nonatomic, readonly) NSString* identifier;
```

to

```objc
@property (nonatomic, readonly) NSUserInterfaceItemIdentifier identifier;
```

may be a quicker (but dirtier?) way, since `NSUserInterfaceItemIdentifier` in Objective-C is `typedef`-ed as `NSString*`.

**Comment by lhc70000** [comment]
I'd love to see a swift version of this project! And if you want, I can help translating it to Swift :D

**Comment by lhc70000** [comment]
> Ah, the NSUserInterfaceItemIdentifier is an alias for NSString! So should we just modify the README.md?

No, in Swift `NSUserInterfaceItemIdentifier` is a struct, so it's impossible to use it without changing the code in `MASPreferences`.

**Comment by shpakovski** [comment]
> I'd love to see a swift version of this project!
Let’s wait for official release of 4.0 and Xcode 9.0 🙂

If we replace `NSString *` by `NSUserInterfaceItemIdentifier` it won’t ever build in Xcode 8.0. So it’s probably better to convert it into `id` / `Any`.

**Comment by lhc70000** [comment]
Alright, thanks in advance!

**Comment by saagarjha** [comment]
@shpakovski How about something like [this](https://github.com/saagarjha/MASPreferences/commit/accc8fd5794e076a0b9b976f86324e34df4317e4#diff-ea7d951f3295553f702d4358cf6e9391)? It retains type safety and works in both Xcode 8 and 9.

**Comment by shpakovski** [comment]
@lhc70000 @saagarjha Thanks a lot, this should be fixed in 7b656d2d6b9161baeed4aadcc61d62c11c6839a1!

**Comment by sorbits** [comment]
Hi @shpakovski, I am late to this one, but I think your original suggestion of renaming `identifier` to `toolbarItemIdentifier` (or similar) is the best solution, despite breaking compatibility, but when people upgrade, they will get a compiler warning, so it should cause minimal problems.

The reason is that at run-time we now have two protocols declaring and _using_ the same property, which means that anyone implementing `identifier` as read-only (for `MASPreferencesViewController` conformance) are effectively breaking `NSUserInterfaceItemIdentification` (where the property is read/write).

**Comment by shpakovski** [comment]
Hey Alan! Should the `identifier` remain of type `NSUserInterfaceItemIdentifier`? I quite like it 🙂

**Comment by sorbits** [comment]
I think we should keep it as `NSString` because we use it e.g. to generate user defaults keys (which are strings), so calling it something other than a string to me is confusing and I actually wonder why Apple decided to introduce a new type alias for their identifier when this one is also very obviously meant to be a string (that you can enter in Interface Builder).

**Comment by sorbits** [comment]
As a follow-up, I do not think `identifier` should be nullable (as done in dc30f9b4d4761d56d57252eba131449c233b16fc), as we e.g. store them in arrays w/o any checks.

As for the name, I am a bit torn here regarding `toolbarItemIdentifier` because we use them to identify preferences views (as well as toolbar items), so it is really a `preferencesViewIdentifier` but there is no precedence for calling anything `preferencesView`, it also seems slightly redundant to have a `preferencesViewIdentifier` in a `MASPreferencesViewController` protocol implementation, but I guess that is Objective-C namespacing (and there is precedence for such name redundancy).

I guess `preferencesViewIdentifier` is OK… if you give me the thumbs up, I can push a commit with this change, and also remove the `nullable`.

**Comment by shpakovski** [comment]
Thanks a lot, how about `viewIdentifier`?

**Comment by sorbits** [comment]
OK, I went with `viewIdentifier`.

I did not update the demo project, would appreciate if you can take care of that.

**Comment by shpakovski** [comment]
I will, cheers!
